### ISSUE TITLE
ModOrganizerInstallFolder\plugins\creation_organizer\creationorganizer.json was not found. Please create and configure the JSON file

### ISSUE THREAD

**Issue by Ratione** [weds4/creation_organizer#1]
This is despite the fact that one of the provided JSON files from the download section is placed in the proper location in the plugins\creation_organizer folder.

Running MO2 on Ubuntu

**Comment by weds4** [comment]
Probably related to using Ubuntu. My plugin is written assuming the user is on Windows.

**Comment by weds4** [comment]
Fixing this might be as simple as re-writing 
`JSON_PATH = ".\\plugins\\creation_organizer\\creation_organizer.json"`
as
`JSON_PATH = "./plugins/creation_organizer/creation_organizer.json"`
in the `"\plugins\creation_organizer\logic\co_constants.py"` line 5, but I don't have any way to test it and don't have any better guesses after that. Feel free to try.

**Comment by StuffOfSonny** [comment]
> Fixing this might be as simple as re-writing `JSON_PATH = ".\\plugins\\creation_organizer\\creation_organizer.json"` as `JSON_PATH = "./plugins/creation_organizer/creation_organizer.json"` in the `"\plugins\creation_organizer\logic\co_constants.py"` line 5, but I don't have any way to test it and don't have any better guesses after that. Feel free to try.

Can confirm this does not fix it.

**Comment by StuffOfSonny** [comment]
By manually specifying the full path to the .JSON (`/home/c/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/plugins/creation_organizer/creation_organizer.json` in my case), I can get the plugin to run.

However, in my case it errors out because I have Mod Organizer 2 installed on my bootdrive, and Skyrim intalled to my Game Drive.
